//! Golden data (master plan §5.6). `cases.json` lists images, answer recipes, player recipes
//! with the score range each must land in, and scoring probes; `expected.json` stores hashes
//! and full Score JSON strings. Native (this module) and wasm (`engine/wasm/test/golden.test.mjs`)
//! must reproduce it exactly.
//!
//! Version ownership (enforced by [`unbumped_changes`]):
//! - decoded images and every 2048 render (answer and players) → `ENGINE_VERSION`
//! - scoring images, Score JSON and scoring sizes of cases → either version (a render change
//!   moves them too)
//! - probes, `scoring_params`, `long_edge` → `SCORING_VERSION` only. Probe inputs are generated
//!   from integer formulas, never decoded or rendered, so any change in a probe result is a
//!   scoring change.
//! - a removed (or renamed) image, case or player → any version bump; a removed (or renamed)
//!   probe → `SCORING_VERSION`
//! - a version change of a pixel-deciding crate in `engine/Cargo.lock` ([`PIXEL_CRATES`]) →
//!   the version that owns it, even when every golden output stays the same

use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use clap::Subcommand;
use engine_core::buffer::Rgba8;
use engine_core::hash::sha256_hex;
use engine_core::region::RegionSpec;
use engine_core::render::{render_rgba8, RenderContext};
use engine_core::score::{scoring_params, ScoringReference};
use engine_core::{
    scoring_image, ENGINE_VERSION, SCHEMA_VERSION, SCORING_LONG_EDGE, SCORING_VERSION,
};
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::{load_image, load_recipe};

#[derive(Subcommand)]
pub(crate) enum GoldenCmd {
    /// Recompute and write `expected.json`. Refuses changes that keep the same versions.
    Write {
        #[arg(long, default_value = "engine/golden")]
        dir: PathBuf,
    },
    /// Recompute and compare with `expected.json`; on any failure write `--actual-out`.
    Check {
        #[arg(long, default_value = "engine/golden")]
        dir: PathBuf,
        #[arg(long)]
        actual_out: Option<PathBuf>,
    },
    /// Fail when `head` changes or drops results relative to `base` without a version bump.
    Guard {
        #[arg(long)]
        base: PathBuf,
        #[arg(long)]
        head: PathBuf,
        /// `engine/Cargo.lock` at the base commit (with `--head-lock`: crate version check).
        #[arg(long, requires = "head_lock")]
        base_lock: Option<PathBuf>,
        /// `engine/Cargo.lock` at the head commit.
        #[arg(long, requires = "base_lock")]
        head_lock: Option<PathBuf>,
    },
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct CaseFile {
    images: BTreeMap<String, String>,
    cases: Vec<Case>,
    probes: Vec<Probe>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Case {
    name: String,
    image: String,
    answer: String,
    seed: u32,
    /// Expected `D_E >= 3`. Ineligible cases document the rule (score 0, never 100).
    eligible: bool,
    players: BTreeMap<String, Player>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Player {
    recipe: String,
    /// Inclusive `[min, max]` the correction score must land in.
    score: [u8; 2],
}

/// A scoring-only input: original, answer and player are generated by [`probe_rgba8`].
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Probe {
    name: String,
    width: u32,
    height: u32,
    /// Original = answer shifted by ±`shift` per channel.
    shift: u32,
    /// Player = answer plus pseudo-noise in `[-noise, noise]`.
    noise: u32,
    /// Inclusive `[min, max]` the correction score must land in.
    score: [u8; 2],
}

#[derive(Clone, Copy)]
enum ProbeRole {
    Original,
    Answer,
    Player,
}

/// Integer-only probe pixels; `engine/wasm/test/golden.test.mjs` has the same formula.
fn probe_rgba8(p: &Probe, role: ProbeRole) -> Result<Rgba8> {
    let (w, h) = (p.width, p.height);
    let mut data = Vec::with_capacity(w as usize * h as usize * 4);
    for y in 0..h {
        for x in 0..w {
            let answer = [
                x * 255 / w.saturating_sub(1).max(1),
                y * 255 / h.saturating_sub(1).max(1),
                ((x / 16 + y / 16) % 2) * 160 + 48,
            ];
            for (c, a) in (0u32..).zip(answer) {
                let a = i64::from(a);
                let v = match role {
                    ProbeRole::Answer => a,
                    ProbeRole::Original if c == 1 => a - i64::from(p.shift),
                    ProbeRole::Original => a + i64::from(p.shift),
                    ProbeRole::Player => {
                        let span = 2 * p.noise + 1;
                        a + i64::from((x * 31 + y * 17 + c * 7) % span) - i64::from(p.noise)
                    }
                };
                data.push(v.clamp(0, 255) as u8);
            }
            data.push(255);
        }
    }
    Ok(Rgba8::new(w, h, data)?)
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ImageEntry {
    width: u32,
    height: u32,
    sha256_rgba8: String,
}

/// One submission's results: its 2048 render, its scoring image and its Score JSON.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct PlayerEntry {
    /// SHA-256 of the full-resolution RGBA8 that was submitted.
    render_sha256: String,
    /// SHA-256 of its 1024 scoring image.
    scoring_sha256: String,
    /// Exact `serde_json::to_string(&Score)`.
    score_json: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct CaseEntry {
    answer_sha256: String,
    answer_scoring_sha256: String,
    scoring_width: u32,
    scoring_height: u32,
    /// Player name → results. Includes the reserved `original` and `answer`.
    players: BTreeMap<String, PlayerEntry>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ProbeEntry {
    scoring_width: u32,
    scoring_height: u32,
    answer_scoring_sha256: String,
    player_scoring_sha256: String,
    score_json: String,
}

/// `scoring_params` as stored: untyped JSON, so snapshots written by other builds still parse.
/// Numbers compare by value (`5` equals `5.0`) because a round trip through JavaScript drops
/// the `.0` that serde writes for floats.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(transparent)]
pub(crate) struct Params(Value);

impl PartialEq for Params {
    fn eq(&self, other: &Self) -> bool {
        json_eq(&self.0, &other.0)
    }
}

/// JSON equality with numbers compared as f64.
fn json_eq(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => x.as_f64() == y.as_f64(),
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(v, w)| json_eq(v, w))
        }
        (Value::Object(x), Value::Object(y)) => {
            x.len() == y.len()
                && x.iter()
                    .all(|(k, v)| y.get(k).is_some_and(|w| json_eq(v, w)))
        }
        _ => a == b,
    }
}

/// `expected.json`. Also the reader for OLD snapshots (guard base, `golden write`), so it must
/// not depend on today's types: `scoring_params` stays untyped JSON, and fields added later
/// must be `#[serde(default)]` so older files still parse.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct Expected {
    engine_version: String,
    scoring_version: String,
    schema_version: u32,
    scoring_params: Params,
    long_edge: u32,
    images: BTreeMap<String, ImageEntry>,
    cases: BTreeMap<String, CaseEntry>,
    #[serde(default)]
    probes: BTreeMap<String, ProbeEntry>,
}

/// Where a golden computation failed. Written to `--actual-out` as `{"failure": …}`.
#[derive(Debug, PartialEq, Eq, Serialize)]
pub(crate) struct Failure {
    case: Option<String>,
    player: Option<String>,
    stage: &'static str,
    error: String,
}

impl fmt::Display for Failure {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let case = self.case.as_deref().unwrap_or("-");
        let player = self.player.as_deref().unwrap_or("-");
        write!(
            f,
            "case {case} / player {player} / {}: {}",
            self.stage, self.error
        )
    }
}

impl std::error::Error for Failure {}

/// Failure context for one step.
#[derive(Clone, Copy)]
struct At<'a> {
    case: Option<&'a str>,
    player: Option<&'a str>,
    stage: &'static str,
}

fn at<'a>(case: Option<&'a str>, player: Option<&'a str>, stage: &'static str) -> At<'a> {
    At {
        case,
        player,
        stage,
    }
}

impl At<'_> {
    fn fail(self, error: String) -> Failure {
        Failure {
            case: self.case.map(str::to_owned),
            player: self.player.map(str::to_owned),
            stage: self.stage,
            error,
        }
    }

    fn on<T, E: Into<anyhow::Error>>(self, r: Result<T, E>) -> Result<T, Failure> {
        r.map_err(|e| self.fail(format!("{:#}", e.into())))
    }

    fn check(self, ok: bool, msg: impl FnOnce() -> String) -> Result<(), Failure> {
        if ok {
            Ok(())
        } else {
            Err(self.fail(msg()))
        }
    }
}

fn entry(submitted: &Rgba8, score: &engine_core::score::Score) -> Result<PlayerEntry> {
    Ok(PlayerEntry {
        render_sha256: sha256_hex(submitted.data()),
        scoring_sha256: sha256_hex(scoring_image(submitted, SCORING_LONG_EDGE)?.data()),
        score_json: serde_json::to_string(score)?,
    })
}

/// A repeated name would silently overwrite the earlier result in the snapshot maps.
fn reject_duplicates<'a>(
    ctx: At<'_>,
    kind: &str,
    names: impl Iterator<Item = &'a str>,
) -> Result<(), Failure> {
    let mut seen = std::collections::BTreeSet::new();
    for name in names {
        ctx.check(seen.insert(name), || {
            format!("duplicate {kind} name `{name}` in cases.json")
        })?;
    }
    Ok(())
}

fn compute(dir: &Path) -> Result<Expected, Failure> {
    let top = at(None, None, "read cases.json");
    let text = top.on(fs::read_to_string(dir.join("cases.json")))?;
    let spec: CaseFile = top.on(serde_json::from_str(&text))?;
    top.check(!spec.images.is_empty() && !spec.cases.is_empty(), || {
        "cases.json has no images or cases".to_owned()
    })?;
    reject_duplicates(top, "case", spec.cases.iter().map(|c| c.name.as_str()))?;
    reject_duplicates(top, "probe", spec.probes.iter().map(|p| p.name.as_str()))?;

    let mut decoded = BTreeMap::new();
    let mut images = BTreeMap::new();
    for (name, file) in &spec.images {
        let img = at(None, None, "decode image").on(load_image(&dir.join(file)))?;
        images.insert(
            name.clone(),
            ImageEntry {
                width: img.width(),
                height: img.height(),
                sha256_rgba8: sha256_hex(img.data()),
            },
        );
        decoded.insert(name.clone(), img);
    }

    let mut cases = BTreeMap::new();
    for case in &spec.cases {
        let src = at(Some(&case.name), None, "image").on(decoded
            .get(&case.image)
            .ok_or_else(|| anyhow::anyhow!("unknown image `{}`", case.image)))?;
        cases.insert(case.name.clone(), compute_case(dir, case, src)?);
    }
    let mut probes = BTreeMap::new();
    for probe in &spec.probes {
        probes.insert(probe.name.clone(), compute_probe(probe)?);
    }

    let params = at(None, None, "scoring params").on(serde_json::to_value(scoring_params()))?;
    Ok(Expected {
        engine_version: ENGINE_VERSION.to_owned(),
        scoring_version: SCORING_VERSION.to_owned(),
        schema_version: SCHEMA_VERSION,
        scoring_params: Params(params),
        long_edge: SCORING_LONG_EDGE,
        images,
        cases,
        probes,
    })
}

/// Answer, original and every player of one case, with the property checks.
fn compute_case(dir: &Path, case: &Case, src: &Rgba8) -> Result<CaseEntry, Failure> {
    let full = RegionSpec::Full {};
    let n = case.name.as_str();
    let here = |stage| at(Some(n), None, stage);
    here("properties").check(!case.eligible || !case.players.is_empty(), || {
        "eligible cases need player recipes".to_owned()
    })?;
    let ctx = RenderContext { seed: case.seed };
    let recipe = here("load answer recipe").on(load_recipe(&dir.join(&case.answer)))?;
    let answer = here("render answer").on(render_rgba8(src, &recipe, &ctx))?;
    let reference = here("scoring reference").on(ScoringReference::new(src, &answer, &full))?;

    let s_answer = at(Some(n), Some("answer"), "score").on(reference.score(&answer, None))?;
    let s_original = at(Some(n), Some("original"), "score").on(reference.score(src, None))?;
    let props = here("properties");
    props.check(s_answer.eligible == case.eligible, || {
        format!("eligible={}", s_answer.eligible)
    })?;
    if case.eligible {
        props.check(s_answer.perfect && s_answer.correction_score == 100, || {
            "answer != 100".to_owned()
        })?;
        props.check(s_original.correction_score == 0, || {
            "original != 0".to_owned()
        })?;
    } else {
        props.check(s_answer.correction_score == 0, || {
            "ineligible must score 0".to_owned()
        })?;
    }
    let mut players = BTreeMap::new();
    let record = here("hash results");
    players.insert("answer".to_owned(), record.on(entry(&answer, &s_answer))?);
    players.insert("original".to_owned(), record.on(entry(src, &s_original))?);
    for (name, player) in &case.players {
        let p_at = |stage| at(Some(n), Some(name.as_str()), stage);
        p_at("properties").check(!players.contains_key(name), || {
            format!("player name `{name}` is reserved")
        })?;
        let recipe = p_at("load player recipe").on(load_recipe(&dir.join(&player.recipe)))?;
        let p = p_at("render player").on(render_rgba8(src, &recipe, &ctx))?;
        let s = p_at("score").on(reference.score(&p, None))?;
        let [lo, hi] = player.score;
        p_at("properties").check((lo..=hi).contains(&s.correction_score), || {
            format!("score {} outside [{lo}, {hi}]", s.correction_score)
        })?;
        players.insert(name.clone(), p_at("hash results").on(entry(&p, &s))?);
    }
    let a = reference.answer_scoring();
    Ok(CaseEntry {
        answer_sha256: sha256_hex(answer.data()),
        answer_scoring_sha256: sha256_hex(a.data()),
        scoring_width: a.width(),
        scoring_height: a.height(),
        players,
    })
}

/// One scoring probe: generated inputs, no decode and no render.
fn compute_probe(probe: &Probe) -> Result<ProbeEntry, Failure> {
    let full = RegionSpec::Full {};
    let here = |stage| at(None, Some(probe.name.as_str()), stage);
    let gen = here("generate probe");
    let original = gen.on(probe_rgba8(probe, ProbeRole::Original))?;
    let answer = gen.on(probe_rgba8(probe, ProbeRole::Answer))?;
    let player = gen.on(probe_rgba8(probe, ProbeRole::Player))?;
    let reference =
        here("scoring reference").on(ScoringReference::new(&original, &answer, &full))?;
    let s = here("score").on(reference.score(&player, None))?;
    let [lo, hi] = probe.score;
    here("properties").check((lo..=hi).contains(&s.correction_score), || {
        format!("score {} outside [{lo}, {hi}]", s.correction_score)
    })?;
    let player_scoring = here("scoring image").on(scoring_image(&player, SCORING_LONG_EDGE))?;
    let a = reference.answer_scoring();
    Ok(ProbeEntry {
        scoring_width: a.width(),
        scoring_height: a.height(),
        answer_scoring_sha256: sha256_hex(a.data()),
        player_scoring_sha256: sha256_hex(player_scoring.data()),
        score_json: here("serialize").on(serde_json::to_string(&s))?,
    })
}

fn read_expected(path: &Path) -> Result<Expected, Failure> {
    let here = at(None, None, "read expected.json");
    let text = here.on(fs::read_to_string(path))?;
    here.on(serde_json::from_str(&text))
}

/// Score JSON without its version fields: probes compare scores across an `ENGINE_VERSION`
/// bump, which rewrites `engine_version` inside every Score.
fn score_without_versions(json: &str) -> Value {
    let mut v: Value = serde_json::from_str(json).unwrap_or(Value::String(json.to_owned()));
    if let Value::Object(map) = &mut v {
        map.remove("engine_version");
        map.remove("scoring_version");
    }
    v
}

/// Results that changed or disappeared between `base` and `head` without the version bump
/// that owns them (see the module docs for the rules).
pub(crate) fn unbumped_changes(base: &Expected, head: &Expected) -> Vec<String> {
    let engine_same = base.engine_version == head.engine_version;
    let scoring_same = base.scoring_version == head.scoring_version;
    let any_same = engine_same && scoring_same;
    let mut problems = Vec::new();
    let mut flag = |cond: bool, what: String, need: &str| {
        if cond {
            problems.push(format!("{what} without {need} bump"));
        }
    };

    flag(
        scoring_same && base.scoring_params != head.scoring_params,
        "scoring_params changed".into(),
        "SCORING_VERSION",
    );
    flag(
        scoring_same && base.long_edge != head.long_edge,
        "long_edge changed".into(),
        "SCORING_VERSION",
    );
    for (name, b) in &base.images {
        match head.images.get(name) {
            None => flag(any_same, format!("images.{name} removed"), "a version"),
            Some(h) => flag(
                engine_same && h != b,
                format!("images.{name} changed"),
                "ENGINE_VERSION",
            ),
        }
    }
    for (name, b) in &base.cases {
        let Some(h) = head.cases.get(name) else {
            flag(any_same, format!("cases.{name} removed"), "a version");
            continue;
        };
        flag(
            engine_same && h.answer_sha256 != b.answer_sha256,
            format!("cases.{name}.answer_sha256 changed"),
            "ENGINE_VERSION",
        );
        let scoring_changed = h.answer_scoring_sha256 != b.answer_scoring_sha256
            || (h.scoring_width, h.scoring_height) != (b.scoring_width, b.scoring_height);
        flag(
            any_same && scoring_changed,
            format!("cases.{name} scoring image changed"),
            "a version",
        );
        for (player, bp) in &b.players {
            let path = format!("cases.{name}.players.{player}");
            let Some(hp) = h.players.get(player) else {
                flag(any_same, format!("{path} removed"), "a version");
                continue;
            };
            flag(
                engine_same && hp.render_sha256 != bp.render_sha256,
                format!("{path}.render_sha256 changed"),
                "ENGINE_VERSION",
            );
            flag(
                any_same && hp.scoring_sha256 != bp.scoring_sha256,
                format!("{path}.scoring_sha256 changed"),
                "a version",
            );
            flag(
                any_same && hp.score_json != bp.score_json,
                format!("{path}.score_json changed"),
                "a version",
            );
        }
    }
    for (name, b) in &base.probes {
        let Some(h) = head.probes.get(name) else {
            flag(
                scoring_same,
                format!("probes.{name} removed"),
                "SCORING_VERSION",
            );
            continue;
        };
        let changed = (h.scoring_width, h.scoring_height) != (b.scoring_width, b.scoring_height)
            || h.answer_scoring_sha256 != b.answer_scoring_sha256
            || h.player_scoring_sha256 != b.player_scoring_sha256
            || score_without_versions(&h.score_json) != score_without_versions(&b.score_json);
        flag(
            scoring_same && changed,
            format!("probes.{name} changed"),
            "SCORING_VERSION",
        );
    }
    problems
}

/// Which version owns a crate's output.
#[derive(Clone, Copy)]
enum Owner {
    /// Decoding: changes decoded pixels and every render.
    Engine,
    /// Used by both the render and the scoring math.
    Both,
}

/// Crates whose code decides pixel or score values (master plan §5.3). Their version in
/// `engine/Cargo.lock` may only change together with the owning version bump.
const PIXEL_CRATES: [(&str, Owner); 6] = [
    ("zune-jpeg", Owner::Engine),
    ("zune-core", Owner::Engine),
    ("png", Owner::Engine),
    ("fdeflate", Owner::Engine),
    ("miniz_oxide", Owner::Engine),
    ("libm", Owner::Both),
];

/// Sorted versions of `name` in a Cargo.lock (several versions can coexist).
fn lock_versions(lock: &str, name: &str) -> Vec<String> {
    let wanted = format!("name = \"{name}\"");
    let mut lines = lock.lines().map(str::trim);
    let mut versions = Vec::new();
    while let Some(line) = lines.next() {
        if line == wanted {
            if let Some(v) = lines
                .next()
                .and_then(|l| l.strip_prefix("version = \""))
                .and_then(|l| l.strip_suffix('"'))
            {
                versions.push(v.to_owned());
            }
        }
    }
    versions.sort();
    versions
}

/// [`PIXEL_CRATES`] whose locked version changed between `base` and `head` without the
/// owning version bump. Catches dependency updates that keep today's golden outputs.
pub(crate) fn crate_changes(
    base_lock: &str,
    head_lock: &str,
    base: &Expected,
    head: &Expected,
) -> Vec<String> {
    let engine_same = base.engine_version == head.engine_version;
    let scoring_same = base.scoring_version == head.scoring_version;
    PIXEL_CRATES
        .iter()
        .filter_map(|&(name, owner)| {
            let (b, h) = (
                lock_versions(base_lock, name),
                lock_versions(head_lock, name),
            );
            let need = match owner {
                Owner::Engine if engine_same => "ENGINE_VERSION",
                Owner::Both if engine_same || scoring_same => "ENGINE_VERSION and SCORING_VERSION",
                _ => return None,
            };
            (b != h).then(|| {
                format!(
                    "Cargo.lock {name} {} -> {} without {need} bump",
                    b.join(","),
                    h.join(",")
                )
            })
        })
        .collect()
}

/// JSON paths where `actual` differs from `expected` (for the failure log).
fn differences(expected: &Value, actual: &Value, path: &str, out: &mut Vec<String>) {
    match (expected, actual) {
        (Value::Object(e), Value::Object(a)) => {
            for key in e.keys().chain(a.keys().filter(|k| !e.contains_key(*k))) {
                let p = format!("{path}.{key}");
                match (e.get(key), a.get(key)) {
                    (Some(ev), Some(av)) => differences(ev, av, &p, out),
                    _ => out.push(p),
                }
            }
        }
        _ if !json_eq(expected, actual) => out.push(path.to_owned()),
        _ => {}
    }
}

fn write_atomically(path: &Path, value: &Expected) -> Result<()> {
    let tmp = path.with_extension("json.tmp");
    fs::write(&tmp, serde_json::to_string_pretty(value)? + "\n")?;
    fs::rename(&tmp, path)?;
    Ok(())
}

fn check(dir: &Path, actual_out: Option<&Path>) -> Result<()> {
    let report = |text: String| -> Result<()> {
        if let Some(out) = actual_out {
            fs::write(out, text)?;
            eprintln!("actual written to {}", out.display());
        }
        Ok(())
    };
    let failure = |f: Failure| -> Result<()> {
        report(serde_json::to_string_pretty(
            &serde_json::json!({ "failure": &f }),
        )?)?;
        Err(f.into())
    };
    let actual = match compute(dir) {
        Ok(a) => a,
        Err(f) => return failure(f),
    };
    let expected = match read_expected(&dir.join("expected.json")) {
        Ok(e) => e,
        Err(f) => return failure(f),
    };
    if actual != expected {
        report(serde_json::to_string_pretty(&actual)? + "\n")?;
        let mut diff = Vec::new();
        differences(
            &serde_json::to_value(&expected)?,
            &serde_json::to_value(&actual)?,
            "",
            &mut diff,
        );
        bail!(
            "golden mismatch: engine output differs from expected.json at\n{}",
            diff.join("\n")
        );
    }
    println!(
        "golden: ok ({} cases, {} probes)",
        expected.cases.len(),
        expected.probes.len()
    );
    Ok(())
}

pub(crate) fn run(cmd: GoldenCmd) -> Result<()> {
    match cmd {
        GoldenCmd::Write { dir } => {
            let head = compute(&dir)?;
            let path = dir.join("expected.json");
            if path.exists() {
                let problems = unbumped_changes(&read_expected(&path)?, &head);
                if !problems.is_empty() {
                    bail!("refusing to write:\n{}", problems.join("\n"));
                }
            }
            write_atomically(&path, &head)?;
            println!("wrote {}", path.display());
        }
        GoldenCmd::Check { dir, actual_out } => check(&dir, actual_out.as_deref())?,
        GoldenCmd::Guard {
            base,
            head,
            base_lock,
            head_lock,
        } => {
            let (base, head) = (read_expected(&base)?, read_expected(&head)?);
            let mut problems = unbumped_changes(&base, &head);
            if let (Some(bl), Some(hl)) = (base_lock, head_lock) {
                let read = |p: &Path| {
                    fs::read_to_string(p).with_context(|| format!("read {}", p.display()))
                };
                problems.extend(crate_changes(&read(&bl)?, &read(&hl)?, &base, &head));
            }
            if !problems.is_empty() {
                bail!("{}", problems.join("\n"));
            }
            println!("golden guard: ok");
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn player(tag: &str) -> PlayerEntry {
        PlayerEntry {
            render_sha256: format!("render-{tag}"),
            scoring_sha256: format!("scoring-{tag}"),
            score_json: format!(
                "{{\"correction_score\":50,\"engine_version\":\"engine-0.1.0\",\"scoring_version\":\"scoring-0.1.0\",\"tag\":\"{tag}\"}}"
            ),
        }
    }

    fn sample() -> Expected {
        let case = CaseEntry {
            answer_sha256: "a".into(),
            answer_scoring_sha256: "b".into(),
            scoring_width: 4,
            scoring_height: 3,
            players: BTreeMap::from([("half".to_owned(), player("half"))]),
        };
        let probe = ProbeEntry {
            scoring_width: 4,
            scoring_height: 3,
            answer_scoring_sha256: "pa".into(),
            player_scoring_sha256: "pp".into(),
            score_json: player("probe").score_json,
        };
        Expected {
            engine_version: "engine-0.1.0".into(),
            scoring_version: "scoring-0.1.0".into(),
            schema_version: 1,
            scoring_params: Params(serde_json::to_value(scoring_params()).unwrap()),
            long_edge: 1024,
            images: BTreeMap::from([(
                "img".to_owned(),
                ImageEntry {
                    width: 4,
                    height: 3,
                    sha256_rgba8: "c".into(),
                },
            )]),
            cases: BTreeMap::from([("case".to_owned(), case)]),
            probes: BTreeMap::from([("probe".to_owned(), probe)]),
        }
    }

    fn case(e: &mut Expected) -> &mut CaseEntry {
        e.cases.get_mut("case").unwrap()
    }

    fn half(e: &mut Expected) -> &mut PlayerEntry {
        case(e).players.get_mut("half").unwrap()
    }

    fn probe(e: &mut Expected) -> &mut ProbeEntry {
        e.probes.get_mut("probe").unwrap()
    }

    fn params(e: &mut Expected) -> &mut serde_json::Map<String, Value> {
        e.scoring_params.0.as_object_mut().unwrap()
    }

    fn bump_engine(e: &mut Expected) {
        e.engine_version = "engine-0.2.0".into();
    }

    fn bump_scoring(e: &mut Expected) {
        e.scoring_version = "scoring-0.2.0".into();
    }

    fn problems(edit: impl FnOnce(&mut Expected)) -> usize {
        let mut head = sample();
        edit(&mut head);
        unbumped_changes(&sample(), &head).len()
    }

    #[test]
    fn identical_results_pass() {
        assert_eq!(problems(|_| {}), 0);
    }

    #[test]
    fn render_change_needs_engine_bump() {
        assert_eq!(problems(|h| case(h).answer_sha256 = "x".into()), 1);
        assert_eq!(
            problems(|h| {
                bump_engine(h);
                case(h).answer_sha256 = "x".into();
            }),
            0
        );
    }

    #[test]
    fn render_change_is_not_excused_by_a_scoring_bump() {
        let n = problems(|h| {
            bump_scoring(h);
            case(h).answer_sha256 = "x".into();
        });
        assert_eq!(n, 1);
    }

    #[test]
    fn player_render_change_needs_engine_bump_not_scoring_bump() {
        assert_eq!(problems(|h| half(h).render_sha256 = "x".into()), 1);
        assert_eq!(
            problems(|h| {
                bump_scoring(h);
                half(h).render_sha256 = "x".into();
            }),
            1
        );
        assert_eq!(
            problems(|h| {
                bump_engine(h);
                half(h).render_sha256 = "x".into();
            }),
            0
        );
    }

    #[test]
    fn player_scoring_image_change_needs_a_bump() {
        assert_eq!(problems(|h| half(h).scoring_sha256 = "x".into()), 1);
        assert_eq!(
            problems(|h| {
                bump_scoring(h);
                half(h).scoring_sha256 = "x".into();
            }),
            0
        );
    }

    #[test]
    fn image_change_needs_engine_bump() {
        assert_eq!(
            problems(|h| h.images.get_mut("img").unwrap().sha256_rgba8 = "x".into()),
            1
        );
    }

    #[test]
    fn score_change_needs_a_bump_and_either_bump_excuses_it() {
        let edit = |h: &mut Expected| half(h).score_json = "{}".into();
        assert_eq!(problems(edit), 1);
        assert_eq!(
            problems(|h| {
                bump_scoring(h);
                edit(h);
            }),
            0
        );
    }

    #[test]
    fn scoring_dimension_change_needs_a_bump() {
        assert_eq!(problems(|h| case(h).scoring_width = 5), 1);
    }

    #[test]
    fn scoring_params_change_needs_scoring_bump_even_with_engine_bump() {
        let n = problems(|h| {
            bump_engine(h);
            params(h).insert("t_tile".into(), json!(3.0));
        });
        assert_eq!(n, 1);
    }

    #[test]
    fn scoring_params_change_with_scoring_bump_passes() {
        let n = problems(|h| {
            bump_scoring(h);
            params(h).insert("t_tile".into(), json!(3.0));
        });
        assert_eq!(n, 0);
    }

    #[test]
    fn added_scoring_param_needs_scoring_bump() {
        let add = |h: &mut Expected| {
            params(h).insert("leak_threshold".into(), json!(0.5));
        };
        assert_eq!(problems(add), 1);
        assert_eq!(
            problems(|h| {
                bump_scoring(h);
                add(h);
            }),
            0
        );
    }

    #[test]
    fn removed_scoring_param_needs_scoring_bump() {
        let remove = |h: &mut Expected| {
            params(h).remove("t_tile");
        };
        assert_eq!(problems(remove), 1);
        assert_eq!(
            problems(|h| {
                bump_scoring(h);
                remove(h);
            }),
            0
        );
    }

    #[test]
    fn snapshot_with_other_scoring_params_fields_still_parses() {
        // A base written by an older or newer build: unknown keys kept, missing keys allowed.
        let mut v = serde_json::to_value(sample()).unwrap();
        let p = v["scoring_params"].as_object_mut().unwrap();
        p.remove("t_tile");
        p.insert("retired_knob".into(), json!(7));
        let old: Expected = serde_json::from_value(v).unwrap();
        assert_eq!(unbumped_changes(&old, &sample()).len(), 1);
    }

    #[test]
    fn scoring_params_compare_numbers_by_value() {
        // expected.json rewritten by JavaScript has `"t_tile": 2` where serde wrote `2.0`.
        assert_eq!(
            problems(|h| {
                params(h).insert("t_tile".into(), json!(2));
            }),
            0
        );
    }

    #[test]
    fn snapshot_without_probes_still_parses() {
        let mut v = serde_json::to_value(sample()).unwrap();
        v.as_object_mut().unwrap().remove("probes");
        let old: Expected = serde_json::from_value(v).unwrap();
        assert!(old.probes.is_empty());
    }

    #[test]
    fn long_edge_change_needs_scoring_bump() {
        assert_eq!(problems(|h| h.long_edge = 512), 1);
    }

    #[test]
    fn pure_scoring_change_with_only_an_engine_bump_is_caught_by_the_probes() {
        // The hole AC-S1b closes: a scoring formula change shipped as an ENGINE bump.
        let n = problems(|h| {
            bump_engine(h);
            half(h).score_json = "{\"correction_score\":51}".into();
            probe(h).score_json = probe(h).score_json.replace(":50,", ":51,");
        });
        assert_eq!(n, 1);
        let n = problems(|h| {
            bump_scoring(h);
            probe(h).score_json = probe(h).score_json.replace(":50,", ":51,");
        });
        assert_eq!(n, 0);
    }

    #[test]
    fn probe_scoring_image_change_needs_scoring_bump() {
        assert_eq!(
            problems(|h| {
                bump_engine(h);
                probe(h).player_scoring_sha256 = "x".into();
            }),
            1
        );
    }

    #[test]
    fn engine_bump_alone_does_not_trip_the_probes() {
        // Score JSON carries engine_version; the probe comparison ignores the version fields.
        let n = problems(|h| {
            bump_engine(h);
            probe(h).score_json = probe(h).score_json.replace("engine-0.1.0", "engine-0.2.0");
        });
        assert_eq!(n, 0);
    }

    #[test]
    fn removed_case_player_image_or_probe_needs_a_bump() {
        assert_eq!(problems(|h| h.cases.clear()), 1);
        assert_eq!(problems(|h| case(h).players.clear()), 1);
        assert_eq!(problems(|h| h.images.clear()), 1);
        assert_eq!(problems(|h| h.probes.clear()), 1);
    }

    #[test]
    fn removed_or_renamed_probe_needs_scoring_bump_not_engine_bump() {
        let rename = |h: &mut Expected| {
            let p = h.probes.remove("probe").unwrap();
            h.probes.insert("renamed".into(), p);
        };
        let remove = |h: &mut Expected| h.probes.clear();
        for edit in [&rename as &dyn Fn(&mut Expected), &remove] {
            assert_eq!(
                problems(|h| {
                    bump_engine(h);
                    edit(h);
                }),
                1
            );
            assert_eq!(
                problems(|h| {
                    bump_scoring(h);
                    edit(h);
                }),
                0
            );
        }
    }

    const LOCK: &str = "[[package]]\nname = \"libm\"\nversion = \"0.2.16\"\n\n[[package]]\nname = \"png\"\nversion = \"0.18.1\"\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.229\"\n\n[[package]]\nname = \"zune-jpeg\"\nversion = \"0.5.15\"\n";

    fn crate_problems(from: &str, to: &str, edit: impl FnOnce(&mut Expected)) -> usize {
        let mut head = sample();
        edit(&mut head);
        crate_changes(LOCK, &LOCK.replace(from, to), &sample(), &head).len()
    }

    #[test]
    fn lock_versions_reads_every_version_of_a_crate() {
        let lock = format!("{LOCK}\n[[package]]\nname = \"png\"\nversion = \"0.17.0\"\n");
        assert_eq!(lock_versions(&lock, "png"), ["0.17.0", "0.18.1"]);
        assert!(lock_versions(LOCK, "fdeflate").is_empty());
    }

    #[test]
    fn decoder_version_change_with_same_golden_and_no_bump_fails() {
        let to = "name = \"zune-jpeg\"\nversion = \"0.5.16\"";
        let from = "name = \"zune-jpeg\"\nversion = \"0.5.15\"";
        assert_eq!(crate_problems(from, to, |_| {}), 1);
        assert_eq!(crate_problems(from, to, bump_scoring), 1);
        assert_eq!(crate_problems(from, to, bump_engine), 0);
    }

    #[test]
    fn libm_version_change_needs_both_bumps() {
        let (from, to) = ("version = \"0.2.16\"", "version = \"0.2.17\"");
        assert_eq!(crate_problems(from, to, bump_engine), 1);
        assert_eq!(crate_problems(from, to, bump_scoring), 1);
        assert_eq!(
            crate_problems(from, to, |h| {
                bump_engine(h);
                bump_scoring(h);
            }),
            0
        );
    }

    #[test]
    fn removed_pixel_crate_counts_as_a_change() {
        let png = "[[package]]\nname = \"png\"\nversion = \"0.18.1\"\n\n";
        assert_eq!(crate_problems(png, "", |_| {}), 1);
    }

    #[test]
    fn other_crate_updates_do_not_need_a_bump() {
        assert_eq!(crate_problems("1.0.229", "1.0.230", |_| {}), 0);
    }

    #[test]
    fn renamed_case_counts_as_removal() {
        let n = problems(|h| {
            let c = h.cases.remove("case").unwrap();
            h.cases.insert("renamed".into(), c);
        });
        assert_eq!(n, 1);
    }

    #[test]
    fn new_cases_players_and_probes_do_not_need_a_bump() {
        let n = problems(|h| {
            let extra = h.cases["case"].clone();
            h.cases.insert("new".into(), extra);
            case(h).players.insert("extra".into(), player("extra"));
            let p = h.probes["probe"].clone();
            h.probes.insert("new".into(), p);
        });
        assert_eq!(n, 0);
    }

    #[test]
    fn failure_display_names_case_player_and_stage() {
        let f = at(Some("lake"), Some("b98"), "render player").fail("boom".into());
        assert_eq!(
            f.to_string(),
            "case lake / player b98 / render player: boom"
        );
    }

    #[test]
    fn differences_lists_changed_and_missing_paths() {
        let mut out = Vec::new();
        differences(
            &json!({"a": 1, "b": {"c": 2, "d": 3}}),
            &json!({"a": 1, "b": {"c": 9}, "e": 0}),
            "",
            &mut out,
        );
        assert_eq!(out, [".b.c", ".b.d", ".e"]);
    }

    /// `compute` on a cases.json with the given cases/probes JSON; fails before any image is read.
    fn compute_error(cases: &str, probes: &str) -> String {
        let dir = std::env::temp_dir().join(format!(
            "golden-dup-{}-{}",
            std::process::id(),
            cases.len() + probes.len()
        ));
        fs::create_dir_all(&dir).unwrap();
        let text = format!(
            "{{\"images\":{{\"i\":\"missing.jpg\"}},\"cases\":{cases},\"probes\":{probes}}}"
        );
        fs::write(dir.join("cases.json"), text).unwrap();
        let Err(failure) = compute(&dir) else {
            panic!("duplicate names must fail");
        };
        let err = failure.to_string();
        let _ = fs::remove_dir_all(&dir);
        err
    }

    const CASE: &str =
        r#"{"name":"c","image":"i","answer":"a","seed":0,"eligible":false,"players":{}}"#;

    #[test]
    fn duplicate_case_names_are_rejected_before_computation() {
        let err = compute_error(&format!("[{CASE},{CASE}]"), "[]");
        assert!(err.contains("duplicate case name `c`"), "{err}");
    }

    #[test]
    fn duplicate_probe_names_are_rejected_before_computation() {
        let probes = r#"[{"name":"p","width":8,"height":8,"shift":0,"noise":0,"score":[0,100]},{"name":"p","width":9,"height":8,"shift":0,"noise":0,"score":[0,100]}]"#;
        let err = compute_error(&format!("[{CASE}]"), probes);
        assert!(err.contains("duplicate probe name `p`"), "{err}");
    }
}
