// Tests for engine/golden/verify-sources.mjs on a throwaway directory (deliberately not a git
// repository: the check must not depend on commits, which squash merges discard):
//   node --test engine/golden/test/verify-sources.test.mjs
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { spawnSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const script = resolve(dirname(fileURLToPath(import.meta.url)), '../verify-sources.mjs')
const sha = (algo, data) => createHash(algo).update(data).digest('hex')
const IMAGE = 'pixels'
const HEX64 = 'a'.repeat(64)

/** A golden dir whose sources.json is `edit(spec)`; images/a.jpg is a processed file. */
function fixture(edit = () => {}) {
  const root = mkdtempSync(join(tmpdir(), 'verify-sources-'))
  mkdirSync(join(root, 'engine/golden/images'), { recursive: true })
  writeFileSync(join(root, 'engine/golden/images/a.jpg'), IMAGE)
  const spec = {
    files: {
      'images/a.jpg': {
        sha256: sha('sha256', IMAGE),
        source: 'a',
        processing: 'engine-cli fixture --out-dir <tmp> --width 4 --height 4, then fixture.jpg',
        reproduce: {
          how: 'ci',
          last_ok: '2026-10-07',
          engine_version: 'engine-0.1.0',
          engine_tree: 'b'.repeat(40),
          cargo_lock_sha256: HEX64,
          rustc: 'rustc 1.98.1',
        },
      },
    },
    sources: { a: { sha1: sha('sha1', IMAGE), sha256: sha('sha256', IMAGE) } },
  }
  const cases = { images: { a: 'images/a.jpg' } }
  edit(spec, root, cases)
  writeFileSync(join(root, 'engine/golden/sources.json'), JSON.stringify(spec))
  writeFileSync(join(root, 'engine/golden/cases.json'), JSON.stringify(cases))
  return root
}

function run(root, ...extra) {
  const r = spawnSync(process.execPath, [script, '--dir', join(root, 'engine/golden'), ...extra], { encoding: 'utf8' })
  rmSync(root, { recursive: true, force: true })
  return { code: r.status, out: r.stdout + r.stderr }
}

let tmpCount = 0
/** Writes `data` under `root` and returns its path. */
function writeTmp(root, data) {
  const path = join(root, `tmp-${tmpCount++}`)
  writeFileSync(path, data)
  return path
}

/** Like `run`, with extra arguments computed from the fixture root. */
const runWith = (root, argsOf) => run(root, ...argsOf(root))

test('passes outside any git repository (squash-safe)', () => {
  const r = run(fixture())
  assert.equal(r.code, 0, r.out)
  assert.match(r.out, /ok images\/a\.jpg/)
  assert.doesNotMatch(r.out, /generator/)
})

test('fails when a processed file has no reproduce record', () => {
  const r = run(fixture((s) => delete s.files['images/a.jpg'].reproduce))
  assert.equal(r.code, 1)
  assert.match(r.out, /NO REPRODUCE RECORD images\/a\.jpg/)
})

test('fails on a malformed reproduce record', () => {
  const r = run(fixture((s) => (s.files['images/a.jpg'].reproduce.how = 'auto')))
  assert.equal(r.code, 1)
  assert.match(r.out, /BAD REPRODUCE RECORD images\/a\.jpg/)
})

test('reports a never-reproduced processed file as unverified, not ok', () => {
  const r = run(fixture((s) => (s.files['images/a.jpg'].reproduce.last_ok = null)))
  assert.equal(r.code, 0, r.out)
  assert.match(r.out, /UNVERIFIED reproduce images\/a\.jpg/)
})

test('an original (unprocessed) file needs no reproduce record', () => {
  const r = run(
    fixture((s) => {
      s.files['images/a.jpg'].processing = 'none: original bytes'
      delete s.files['images/a.jpg'].reproduce
    }),
  )
  assert.equal(r.code, 0, r.out)
})

test('--processed passes for a regenerated file with the recorded hash', () => {
  const r = runWith(fixture(), (root) => ['--processed', 'images/a.jpg', writeTmp(root, IMAGE)])
  assert.equal(r.code, 0, r.out)
  assert.match(r.out, /ok processed images\/a\.jpg/)
})

test('--processed fails when the regenerated bytes differ', () => {
  const r = runWith(fixture(), (root) => ['--processed', 'images/a.jpg', writeTmp(root, 'other')])
  assert.equal(r.code, 1)
  assert.match(r.out, /MISMATCH processed images\/a\.jpg sha256/)
})

test('--processed fails for a key that sources.json does not list', () => {
  const r = runWith(fixture(), (root) => ['--processed', 'images/zz.jpg', writeTmp(root, IMAGE)])
  assert.equal(r.code, 1)
  assert.match(r.out, /UNKNOWN processed file images\/zz\.jpg/)
})

test('fails on a missing file', () => {
  const r = run(fixture((s) => (s.files['images/b.jpg'] = { sha256: '0'.repeat(64), processing: 'none: original bytes' })))
  assert.equal(r.code, 1)
  assert.match(r.out, /MISSING images\/b\.jpg/)
})

test('fails on a wrong file hash', () => {
  const r = run(fixture((s) => (s.files['images/a.jpg'].sha256 = '0'.repeat(64))))
  assert.equal(r.code, 1)
  assert.match(r.out, /MISMATCH images\/a\.jpg sha256/)
})

test('fails when a cases.json image has no provenance record', () => {
  const r = run(fixture((s) => delete s.files['images/a.jpg']))
  assert.equal(r.code, 1)
  assert.match(r.out, /NO PROVENANCE for cases\.json image a: images\/a\.jpg/)
})

test('fails on an empty files list', () => {
  const r = run(fixture((s) => (s.files = {})))
  assert.equal(r.code, 1)
  assert.match(r.out, /EMPTY sources\.json files/)
})

test('checks a downloaded source by SHA-1 and SHA-256', () => {
  let root = fixture()
  const ok = run(root, 'a', join(root, 'engine/golden/images/a.jpg'))
  assert.equal(ok.code, 0, ok.out)
  root = fixture((s) => (s.sources.a.sha1 = '0'.repeat(40)))
  const bad = run(root, 'a', join(root, 'engine/golden/images/a.jpg'))
  assert.equal(bad.code, 1)
  assert.match(bad.out, /MISMATCH source a sha1/)
})
